# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('post', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last name')),
                ('token', models.CharField(db_index=True, max_length=15, null=True, unique=True, verbose_name='Token')),
                ('subscribed', models.CharField(blank=True, max_length=2, null=True, verbose_name='Subscribed or not')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
